name: Deploy Github OIDC Shim

on:
  push:
    branches:
      - dd-github-sso

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Install Dependencies
      #   run: npm install
      # - name: Test and Build
      #   run: npm run build-dist
      - name: Deploy to AWS
        uses: apex/actions/aws/sam@master
        with:
          args: |
            pip install awscli --upgrade --user
            pip list -o
            ls -al /usr/local/bin/python
            which python
            which aws
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          COGNITO_REDIRECT_URI: ${{ secrets.COGNITO_REDIRECT_URI }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          OUTPUT_TEMPLATE_FILE: serverless-output.yml
          NODE_ENV: production
          REGION: us-east-1
          STACK_NAME: backend-production-github-oauth
          STACK_OWNER_ARN: ${{ secrets.STACK_OWNER_ARN}}
          STAGE: production
