name: Deploy Github OIDC Shim

on:
  push:
    branches:
      - dd-github-sso

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: GitHub Action for Homebrew
        uses: artemnovichkov/action-homebrew@0.1.0
      - name: Github Acion for Homebrew tap
        uses: izumin5210/action-homebrew-tap@v1.0.0
        with:
          tap: izumin5210/homebrew-tools
          token: ${{ secrets.GITHUB_BREW_TOKEN }}
          tap-token: ${{ secrets.GITHUB_BREW_TAP_TOKEN }}
      - name: Install sam
        run: brew tap aws/tap && brew install aws-sam-cli
      - name: Test & Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: backend-production-github-oauth-bucket
          CI: true
          COGNITO_REDIRECT_URI: https://courier-dev-730438017227.auth.us-east-1.amazoncognito.com/oauth2/idpresponse
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          NODE_ENV: production
          REGION: us-east-1
          STACK_NAME: backend-production-github-oauth
          STAGE: production
        run: npm run deploy
