Resources:
  CustomCognitoIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      AttributeMapping: {
        email: "email",
        gender: "gender",
        locale: "locale",
        name: "name",
        picture: "picture",
        profile: "profile",
        username: "sub"
      }
      ProviderDetails:
        attributes_request_method: POST
        attributes_url_add_attributes: false
        attributes_url: ${self:custom.awsGithubSsoGatewayUri}/user
        authorize_scopes: "openid read:user user:email"
        authorize_url: ${self:custom.awsGithubSsoGatewayUri}/auth
        client_id: ${self:custom.githubClientId}
        client_secret: ${self:custom.githubClientSecret}
        jwks_uri: ${self:custom.awsGithubSsoGatewayUri}/jwt
        oidc_issuer: ${self:custom.awsGithubSsoGatewayUri}
        token_url: ${self:custom.awsGithubSsoGatewayUri}/token
      ProviderName: "GitHub"
      ProviderType: OIDC
      UserPoolId: ${self:custom.awsUserPoolId}
