Resources:
  CustomCognitoIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      AttributeMapping: {
        email: "email",
        gender: "gender",
        locale: "locale",
        name: "name",
        picture: "picture",
        profile: "profile",
        username: "sub"
      }
      ProviderDetails:
        attributes_request_method: POST
        attributes_url:
          Fn::Join:
            - ""
            - - ${self:custom.awsGithubSsoGatewayUri}
              - "/userinfo"
        authorize_scopes: "openid read:user user:email"
        authorize_url:
          Fn::Join:
            - ""
            - - ${self:custom.awsGithubSsoGatewayUri}
              - "/authorize"
        client_id: ${self:custom.githubClientId}
        client_secret: ${self:custom.githubClientSecret}
        jwks_uri:
          Fn::Join:
            - ""
            - - ${self:custom.awsGithubSsoGatewayUri}
              - "/.well-known/jwks.json"
        oidc_issuer: ${self:custom.awsGithubSsoGatewayUri}
        token_url:
          Fn::Join:
            - ""
            - - ${self:custom.awsGithubSsoGatewayUri}
              - "/token"
      ProviderName: "GitHub"
      ProviderType: OIDC
      UserPoolId: ${self:custom.awsUserPoolId}
